image: atlassian/default-image:2
pipelines:
  branches:
    develop:
      - step:
          name: Build and Push Image
          deployment: Dev-ECR
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - cp /opt/atlassian/pipelines/agent/ssh/id_rsa ./id_rsa
            - docker build -t $ECR_NAME .
            - pipe: atlassian/aws-ecr-push-image:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $ECR_NAME
                TAGS: '${LABEL} latest'
      - step:
          name: Deploy to ECS
          image: hanhdevblock/aws-cli:ecs
          deployment: Dev
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - sh /root/ecs-deploy.sh
    release/staging:
      - step:
          name: Build and Push Image
          deployment: Staging-ECR
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - cp /opt/atlassian/pipelines/agent/ssh/id_rsa ./id_rsa
            - docker build -t $ECR_NAME .
            - pipe: atlassian/aws-ecr-push-image:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $ECR_NAME
                TAGS: '${LABEL} latest'
      - step:
          name: Deploy to ECS
          deployment: Staging
          image: hanhdevblock/aws-cli:ecs
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - sh /root/ecs-deploy.sh
    master:
      - step:
          name: Build and Push Image
          deployment: Production-ECR
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - cp /opt/atlassian/pipelines/agent/ssh/id_rsa ./id_rsa
            - docker build -t $ECR_NAME .
            - pipe: atlassian/aws-ecr-push-image:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $ECR_NAME
                TAGS: '${LABEL}'
      - step:
          name: Deploy to ECS
          deployment: Production
          trigger: manual
          image: hanhdevblock/aws-cli:ecs
          script:
            - export LABEL=$BITBUCKET_COMMIT"-"$BITBUCKET_BUILD_NUMBER
            - sh /root/ecs-deploy.sh


